config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  post '/webhook_events/:source', to: 'webhook_events#create'
  #source could be stripe or github or twilio or facebook etc.

  namespace :admin do
    root 'application#index'
    resources :users
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :expenses, only: [:index]
    resources :listings, only: [:index]
    resources :apps, only: [:index]
    resources :leases, only: [:index]
    resources :tickets, only: [:index]
  end

  resources :users, only: [:show]
  resources :categories, only: [:show]
  resources :tags, only: [:show]
  resources :expenses
  resources :tickets, only: [:index, :show, :new, :create]

  resources :properties do
    #resources :expenses, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :comments, only: [:create]
    resources :likes, only: [:create]
  end

  resources :listings do
  end

  resources :apps

  resources :leases do
    resources :payments
    resources :receipts, only: [:index, :show, :destroy]
  end

end

app/models/listing.rb
class Listing < ApplicationRecord
  paginates_per 15

  belongs_to :for_property, class_name: "Property", foreign_key: "property_id"
  has_many :apps, dependent: :destroy
  has_one :landlord, through: :for_property, class_name: "User", foreign_key: "user_id"

  has_many_attached :images

  validates :title, presence: true, length: {minimum: 3}
  validates :rent_amount, presence: true
  validates :security_deposit_amount, presence: true
  validates :available_date, presence: true
  validates :available_area, presence: true
  validates :bedroom, presence: true
  validates :full_bath, presence: true

end

app/controllers/admin/listings_controller.rb
class Admin::ListingsController < Admin::ApplicationController
  def index
      @listings = Listing.all.page params[:page]
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]
  skip_after_action :verify_authorized

  def index
    @listings = Listing.where(property_id: current_user.managed_properties)
    authorize @listings, :index?
  end

  def show
    authorize @listing, :show?
  end

  def new
    @listing = Listing.new
    authorize @listing, :new?
  end

  def create
    @listing = Listing.new(listing_params)
    authorize @listing, :create?
    if @listing.save
      flash[:success] = "Listing created successfully."
      redirect_to listings_path
    else
      flash[:warning] = "Listing not created."
      render "new"
    end
  end

  def edit
    authorize @listing, :edit?
  end

  def update
    authorize @listing, :update?
    if @listing.update(listing_params)
      flash[:success] = "Listing updated."
      redirect_to listings_path
    else
      flash.now[:warning] = "Listing not updated."
      render "edit"
    end
  end

  def destroy
    authorize @listing, :destroy?
    if @listing.destroy
      flash[:danger] = "Listing deleted successfully."
      redirect_to listings_path
    else
      flash[:warning] = "Listing not deleted."
      render listings_path
    end
  end

  private

    def set_listing
      @listing = Listing.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        flash[:danger] = "The page you requested does not exist."
        redirect_to listings_path
    end

    def listing_params

      #ActionController::Parameters.permit_all_parameters = true #To check if this allows all parameters by default. How to do that?

      params.require(:listing).permit(:title,
            :description,
            :contact_phone,
            :contact_email,
            :status,
            :rent_amount,
            :security_deposit_amount,
            :other_amount,
            :start_date,
            :end_date,
            :available_date,
            :rental_terms,
            :utilities_paid,
            :smoking_allowed,
            :approval_required,
            :approval_requirements,
            :pets_allowed,
            :pet_deposit_amount,
            :pet_deposit_description,
            :bedroom,
            :full_bath,
            :half_bath,
            :available_area,
            :bedroom_description,
            :room_description,
            :bathroom_description,
            :kitchen_description,
            :complex_access,
            :style,
            :parking,
            :lot_description,
            :furnished,
            :microwave,
            :dishwasher,
            :fireplace,
            :fireplace_description,
            :oven_type,
            :stove_type,
            :washer_dryer,
            :appliances,
            :swimming_pool,
            :pool_description,
            :flooring_description,
            :exterior_description,
            :heating_description,
            :cooling_description,
            :water_description,
            :energy_features,
            :other_amenities,
            :credit_check_required,
            :criminal_background_check_required,
            :credit_check_required,
            :sexual_offender_check_required,
            :eviction_check_required,
            :virtual_tour_link1,
            :virtual_tour_link2,
            :property_id,
            images: []
          )

    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<!-- Nav tabs -->
<p>
<ul class="nav nav-tabs" id="listingTab" role="tablist">
  <li class="nav-item" role="presentation"><a class="nav-link active" id="home-tab" data-toggle="tab" href="#tabpane1">Listing Information</a></li>
  <li class="nav-item" role="presentation"><a class="nav-link" id="info-tab" data-toggle="tab" href="#tabpane2">Property Information</a></li>
  <li class="nav-item" role="presentation"><a class="nav-link" id="rooms-tab" data-toggle="tab" href="#tabpane3">Rooms</a></li>
  <li class="nav-item" role="presentation"><a class="nav-link" id="lease-tab" data-toggle="tab" href="#tabpane4">Lease Information</a></li>
  <li class="nav-item" role="presentation"><a class="nav-link" id="showing-tab" data-toggle="tab" href="#tabpane5">Showing Information</a></li>
  <li class="nav-item" role="presentation"><a class="nav-link" id="remarks-tab" data-toggle="tab" href="#tabpane6">Remarks/Tour Links</a></li>
  <li class="nav-item" role="presentation"><a class="nav-link" id="remarks-tab" data-toggle="tab" href="#tabpane7">Photos/Video</a></li>
</ul>

<!-- Tab panes -->
<%= simple_form_for(listing) do |p| %>

<div class="tab-content" id="listingTabContent">
  <div class="tab-pane fade show active" id="tabpane1" role="tabpanel">
    <%= render "tabpane1", p: p %>
  </div>
  <div class="tab-pane fade" id="tabpane2" role="tabpanel">
    <%= render "tabpane2", p: p %>
  </div>
  <div class="tab-pane fade" id="tabpane3" role="tabpanel">
    <%= render "tabpane3", p: p %>
  </div>
  <div class="tab-pane fade" id="tabpane4" role="tabpanel">
    <%= render "tabpane4", p: p %>
  </div>
  <div class="tab-pane fade" id="tabpane5" role="tabpanel">
    <%= render "tabpane5", p: p %>
  </div>
  <div class="tab-pane fade" id="tabpane6" role="tabpanel">
    <%= render "tabpane6", p: p %>
  </div>
  <div class="tab-pane fade" id="tabpane7" role="tabpanel">
    <%= render "tabpane7", p: p %>
  </div>
</div>

<%= p.button :submit, class: "btn btn-primary"%> <%= link_to "Cancel", listings_path, class: "btn btn-secondary" %>
<% end %>

app/views/listings/_tabpane1.html.erb
<%# Listing Information %>

  <%= p.association :for_property, collection: User.find(current_user.id).managed_properties.order(:title), label: "Select Property", prompt: true %>
  <%# p.input :property_id, collection: User.find(current_user.id).managed_properties, label: "Select Property", prompt: true %>
  <%= p.input :title %>
  <%= p.input :description %>
  <div class="form-inline">
    <%= p.input :contact_phone %>
    <%= p.input :contact_email %>
  </div>
  <%= p.input :status %>
  <%= p.input :start_date, as: :date, order: [:day, :month, :year] %>
  <%= p.input :end_date, as: :date, order: [:day, :month, :year] %>
  <%= p.input :available_date, as: :date, order: [:day, :month, :year] %>

app/views/listings/_tabpane2.html.erb
<%# Property Information %>
  <%= p.input :available_area, input_html: { min: 0 } %>
  <%= p.input :complex_access %>
  <%= p.input :style %>
  <%= p.input :parking %>
  <%= p.input :lot_description %>
  <%= p.input :furnished %>
  <%= p.input :microwave %>
  <%= p.input :dishwasher %>
  <%= p.input :fireplace, input_html: { min: 0, max: 5, value: 0 } %>
  <%= p.input :fireplace_description %>
  <%= p.input :oven_type %>
  <%= p.input :stove_type %>
  <%= p.input :washer_dryer %>
  <%= p.input :appliances %>
  <%= p.input :swimming_pool, input_html: { min: 0, max: 5, value: 0 } %>
  <%= p.input :pool_description %>
  <%= p.input :flooring_description %>
  <%= p.input :exterior_description %>
  <%= p.input :heating_description %>
  <%= p.input :cooling_description %>
  <%= p.input :water_description %>
  <%= p.input :energy_features %>
  <%= p.input :other_amenities %>

app/views/listings/_tabpane3.html.erb
<%# Rooms %>
  <%= p.input :bedroom, input_html: { min: 0, max: 10 } %>
  <%= p.input :full_bath, input_html: { min: 0, max: 10 } %>
  <%= p.input :half_bath, input_html: { min: 0, max: 10, value: 0 } %>
  <%= p.input :bedroom_description %>
  <%= p.input :room_description %>
  <%= p.input :bathroom_description %>
  <%= p.input :kitchen_description %>

app/views/listings/_tabpane4.html.erb
<%# Lease Information %>
  <div class="form-inline">
    <%= p.input :rent_amount, input_html: { min: 0, step: 0.01 } %>
    <%= p.input :security_deposit_amount, input_html: { min: 0 } %>
    <%= p.input :other_amount, input_html: { min: 0, value: 0 } %>
  </div>
  <div class="form-inline">
    <%= p.input :pets_allowed %>
    <%= p.input :pet_deposit_amount, input_html: { min: 0, value: 0 } %>
  </div>
  <%= p.input :pet_deposit_description %>

  <%= p.input :rental_terms %>
  <%= p.input :utilities_paid %>

  <%= p.input :smoking_allowed %>
  <%= p.input :approval_required %>
  <%= p.input :approval_requirements %>

  <%= p.input :credit_check_required %>
  <%= p.input :criminal_background_check_required %>
  <%= p.input :credit_check_required %>
  <%= p.input :sexual_offender_check_required %>
  <%= p.input :eviction_check_required %>

app/views/listings/_tabpane5.html.erb
<%# Showing Information %>

app/views/listings/_tabpane6.html.erb
<%# Remarks/Tour Links %>

<%= p.input :virtual_tour_link1 %>
<%= p.input :virtual_tour_link2 %>

app/views/listings/_tabpane7.html.erb
<%# Photos/Video %>

<%# if p.images.attached? %>
  <%# p.images.each do |image| %>
    <%# image_tag image, style: "width: 200px; display: block" %>
  <%# end %>
<%# end %>

<div class="field">
  <%= p.label :images %>
  <%= p.file_field :images, multiple: true %>
</div>
<%# p.input :image, as: :file, label: "Upload Image", input_html: { multiple: true }  %>

app/views/listings/edit.html.erb
<% provide(:title, @listing.title) %>

<header>
  <h1>Edit Listing</h1>
</header>

<%= render "form", listing: @listing %>

app/views/listings/index.html.erb
<header>
  <h1>My Listings</h1>
  <ul class="actions">
    <%= link_to "New listing", new_listing_path, class: "new" if policy(Listing).new? %>
  </ul>
</header>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Property</th>
      <th>Title</th>
      <th>Status</th>
      <th>Rent Amt</th>
      <th>Available Date</th>
      <th>Bedrooms/Bathrooms</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @listings.each do |listing| %>
    <tr>
      <td><%= link_to listing.for_property.title, property_path(listing.for_property) %></td>
      <td><%= link_to listing.title, listing_path(listing) %></td>
      <td><%= listing.status  %></td>
      <td><%= listing.rent_amount %></td>
      <td><%= listing.available_date %></td>
      <td><%= listing.bedroom %></td>
      <td><%= link_to "Delete", listing_path(listing), method: :delete, class: "delete", data: {confirm: "Are you sure?"} if policy(listing).destroy? %></td>
      <td><%= link_to 'Edit', edit_listing_path(listing), class: "edit" if policy(listing).edit? %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/listings/new.html.erb
<header>
  <h1>New Listing</h1>
</header>

<%= render "form", listing: @listing %>

app/views/listings/show.html.erb
<% provide(:title, @listing.title) %>

<header>
  <h1><%= @listing.for_property.title %> <%= @listing.title %></h1>

  <ul class="actions">
    <%= link_to "Edit", edit_listing_path(@listing), class: "edit" if policy(@listing).edit? %>
    <%= link_to "Delete", listing_path(@listing), method: :delete, class: "delete", data: {confirm: "Are you sure?"} if policy(@listing).destroy? %>
    <% if @listing.for_property.landlord != current_user %>
      <%= link_to "Apply to rent", new_app_path, class: "apply" %>
    <% end %>
  </ul>
</header>

<div class="row">
    <div class="col-12">
      <h4>Address</h4>
      <p><%= @listing.for_property.address1 %> <%= listing_status(@listing) %></p>

        <p><%= @listing.rent_amount %></p>
        <p><%= @listing.security_deposit_amount %></p>
        <p><%= @listing.available_date %></p>
      <h4>Interior Features</h4>
    </div>

      <div class="">
        <div class="col-6">
          something
        </div>
          another thing
        <div class="col-6">

        </div>
      </div>

      <div class="col-12">


    <p><%= @listing.description %></p>
    <p><%= @listing.contact_phone %></p>
    <p><%= @listing.contact_email %></p>

    <p><%= @listing.other_amount %></p>
    <p><%= @listing.start_date %></p>
    <p><%= @listing.end_date %></p>

    <p><%= @listing.rental_terms %></p>
    <p><%= @listing.utilities_paid %></p>
    <p><%= @listing.smoking_allowed %></p>
    <p><%= @listing.approval_required %></p>
    <p><%= @listing.approval_requirements %></p>
    <p><%= @listing.pets_allowed %></p>
    <p><%= @listing.pet_deposit_amount %></p>
    <p><%= @listing.pet_deposit_description %></p>
    <p><%= @listing.bedroom %></p>
    <p><%= @listing.full_bath %></p>
    <p><%= @listing.half_bath %></p>
    <p><%= @listing.available_area %></p>
    <p><%= @listing.bedroom_description %></p>
    <p><%= @listing.room_description %></p>
    <p><%= @listing.bathroom_description %></p>
    <p><%= @listing.kitchen_description %></p>
    <p><%= @listing.complex_access %></p>
    <p><%= @listing.style %></p>
    <p><%= @listing.parking %></p>
    <p><%= @listing.lot_description %></p>
    <p><%= @listing.furnished %></p>
    <p><%= @listing.microwave %></p>
    <p><%= @listing.dishwasher %></p>
    <p><%= @listing.fireplace %></p>
    <p><%= @listing.fireplace_description %></p>
    <p><%= @listing.oven_type %></p>
    <p><%= @listing.stove_type %></p>
    <p><%= @listing.washer_dryer %></p>
    <p><%= @listing.appliances %></p>
    <p><%= @listing.swimming_pool %></p>
    <p><%= @listing.pool_description %></p>
    <p><%= @listing.flooring_description %></p>
    <p><%= @listing.exterior_description %></p>
    <p><%= @listing.heating_description %></p>
    <p><%= @listing.cooling_description %></p>
    <p><%= @listing.water_description %></p>
    <p><%= @listing.energy_features %></p>
    <p><%= @listing.other_amenities %></p>
    <p><%= @listing.credit_check_required %></p>
    <p><%= @listing.criminal_background_check_required %></p>
    <p><%= @listing.credit_check_required %></p>
    <p><%= @listing.sexual_offender_check_required %></p>
    <p><%= @listing.eviction_check_required %></p>
    <p><%= @listing.virtual_tour_link1 %></p>
    <p><%= @listing.virtual_tour_link2 %></p>
      </div>

      <p>
        <strong>Images:</strong> <br/>
        <% if @listing.images.attached? %>
          <% @listing.images.each do |image| %>
            <%= image_tag image, style: "width: 200px; display: block" %>
            <%= link_to image.filename, image, target: '_blank' %> <br/>
          <% end %>
        <% else %>
          <p>no images</p>
        <% end %>
      </p>
</div>