config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  post '/webhook_events/:source', to: 'webhook_events#create'
  #source could be stripe or github or twilio or facebook etc.

  namespace :admin do
    root 'application#index'
    resources :users
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :expenses, only: [:index]
    resources :listings, only: [:index]
    resources :apps, only: [:index]
    resources :leases, only: [:index]
    resources :tickets, only: [:index]
  end

  resources :users, only: [:show]
  resources :categories, only: [:show]
  resources :tags, only: [:show]
  resources :expenses
  resources :tickets, only: [:index, :show, :new, :create]

  resources :properties do
    #resources :expenses, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :comments, only: [:create]
    resources :likes, only: [:create]
  end

  resources :listings do
  end

  resources :apps

  resources :leases do
    resources :payments
    resources :receipts, only: [:index, :show, :destroy]
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  extend FriendlyId
  friendly_id :name
  paginates_per 5

  has_many :taggings, dependent: :destroy
  has_many :properties, through: :taggings

  def to_s
    name
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  #skip_after_action :verify_authorized

  def show
    @tag = Tag.friendly.find(params[:id])
    @categories = Category.order(:name)
    authorize @tag, :show?
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_tag.html.erb
<%= link_to tag_path(tag) do %>
<span class="tag"><%= fa_icon "hashtag"%><%= tag.name %></span>
<% end %>

app/views/tags/show.html.erb
<% provide(:title, @tag.name ) %>

<header>
  <h1>Properties tagged: <strong><em><%= @tag.name %></em></strong></h1>
</header>

<div class="row">
  <div class="col-3 float-right">
    <div class="nav flex-column nav-pills">
      <h3 class="discover">Discover</h3>
      <ul class="nav-item">
        <li class="<%= "active" if current_page?("/properties")%>"><%= link_to "ALL PROPERTIES", properties_path %> </li>
        <% @categories.each do |category| %>
          <li class="<%= "active" if current_page?("/categories/#{category.id}")%> text-uppercase">
            <%= link_to category.name.upcase, category_path(category) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="col-9 float-left">
    <h4>Discover and apply to your favorite properties right here</h4>

    <% @tag.properties.each do |property| %>
     <div class="col-9">
       <%= link_to property_path(property) do %>
        <div class="properties">
          <div class="row">
            <div class="col-sm-3">
              <%= "Image here" %>
            </div>
            <div class="col-sm-9">
              <h3><%= property.title %></h3>
              <p><%= property.city %></p>
              <p><%= property.state %></p>
              <p><%= property.country %></p>
              <p><%= property_status(property) %></p>
              <p class="index-icons">
                <span><%= fa_icon "comments" %></span>
                <span><%= fa_icon "thumbs-o-up" %></span>
                <span><%= fa_icon "thumbs-o-down" %></span>
              </p>
            </div>
          </div>
        </div>
       <% end %>
     </div>
    <% end %>
    <%# paginate @tag.properties TODO pagination %>
  </div>
</div>