config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  post '/webhook_events/:source', to: 'webhook_events#create'
  #source could be stripe or github or twilio or facebook etc.

  namespace :admin do
    root 'application#index'
    resources :users
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :expenses, only: [:index]
    resources :listings, only: [:index]
    resources :apps, only: [:index]
    resources :leases, only: [:index]
    resources :tickets, only: [:index]
  end

  resources :users, only: [:show]
  resources :categories, only: [:show]
  resources :tags, only: [:show]
  resources :expenses
  resources :tickets, only: [:index, :show, :new, :create]

  resources :properties do
    #resources :expenses, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :comments, only: [:create]
    resources :likes, only: [:create]
  end

  resources :listings do
  end

  resources :apps

  resources :leases do
    resources :payments
    resources :receipts, only: [:index, :show, :destroy]
  end

end

app/models/address.rb
#renter's prior addresses

app/models/app.rb
class App < ApplicationRecord
  paginates_per 15
  belongs_to :listing
  #has_one :landlord, through: :property  #TODO will this work?

  validates :emergency_contact_name, presence: true, length: {minimum: 5}
  validates :emergency_contact_phone, presence: true, length: {minimum: 10}
  validates :emergency_contact_email, presence: true, length: {minimum: 5}

end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  paginates_per 3

  validates :name, presence: true, length: { minimum: 5 }
  validates_uniqueness_of :name

  has_many :properties
end

app/models/comment.rb
class Comment < ApplicationRecord
  paginates_per 5

  belongs_to :property
  belongs_to :author, class_name: "User"

  validates :body, presence: true, length: {minimum: 3}
end

app/models/employer.rb
#renter's prior employers

app/models/expense.rb
class Expense < ApplicationRecord
  paginates_per 15

  belongs_to :for_property, class_name: "Property", foreign_key: "property_id"

  has_many_attached :receipts #TODO receipt model is used for rent receipt.

  validates :title, presence: true, length: {minimum: 3}
  validates :expense_amount, presence: true
  validates :expense_category, presence: true

end

app/models/inventory.rb
#door_keys
#mailbox_keys
#security_cards
#garage_door_remotes
#laundry_room_keys
#gym_keys
#notes Text field

app/models/lease.rb
class Lease < ApplicationRecord
  paginates_per 15
  resourcify #for rolify gem
  
  #TODO
  #has one or more tenants
  #has one or more occupants
  #rental_concession (All Utilities Included, discounted rent amount, one month of free rent, free parking, waived amenity fees, etc.)
  #amenities (community pool, dry-cleaning pickup, package receiving and dog walking etc.)
  #pet addendum or parking addendum terms

  belongs_to :for_property, class_name: "Property", foreign_key: "property_id"
  belongs_to :tenant, class_name: "User", foreign_key: "tenant_id", optional: true
  has_many :receipts, dependent: :destroy

  validates :landlord_name, presence: true, length: {minimum: 5}
  validates :tenant_name, presence: true, length: {minimum: 5}
  validates :tenant_email, presence: true, length: {minimum: 5}
  validates :lease_start_date, presence: true
  validates :lease_end_date, presence: true
  validates :rent_amount, presence: true
  validates :security_deposit, presence: true

  def generate_receipt_number
    "#{id}_#{tenant_name}_#{Time.now.strftime("%b%Y")}"
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :property
  belongs_to :user

  validates_uniqueness_of :user_id, scope: :property

end

app/models/listing.rb
class Listing < ApplicationRecord
  paginates_per 15

  belongs_to :for_property, class_name: "Property", foreign_key: "property_id"
  has_many :apps, dependent: :destroy
  has_one :landlord, through: :for_property, class_name: "User", foreign_key: "user_id"

  has_many_attached :images

  validates :title, presence: true, length: {minimum: 3}
  validates :rent_amount, presence: true
  validates :security_deposit_amount, presence: true
  validates :available_date, presence: true
  validates :available_area, presence: true
  validates :bedroom, presence: true
  validates :full_bath, presence: true

end

app/models/pet.rb
#renter pets

app/models/property.rb
class Property < ApplicationRecord
  searchkick
  attr_accessor :tag_list

  extend FriendlyId
  friendly_id :title, use: :slugged
  paginates_per 3

  belongs_to :landlord, class_name: "User", foreign_key: "user_id"
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :expenses, class_name: "Expense", dependent: :destroy
  has_many :listings, class_name: "Listing", dependent: :destroy
  has_many :leases, class_name: "Lease", dependent: :destroy
  has_many :apps, through: :listings, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :comments, dependent: :destroy
  has_many :tickets  #we want to keep old tickets even if property is deleted. TODO: Check where to assign such tickets if property is deleted.

  has_one_attached :image

  validates :title, presence: true, length: {minimum: 3}
  validates :description, presence: true, length: {minimum: 5}
  validates :address1, presence: true, length: {minimum: 5}
  validates :postal_code, presence: true
  validates :country, presence: true
  validates :category_id, presence: true
  validates :status, presence: true

  def likes_total
    self.likes.where(like: "like").count
  end

  def dislikes_total
    self.likes.where(like: "dislike").count
  end

  def tag_list #this is getting the tags from database
    tags.join(", ")
  end

  def tag_list=(names) #this is getting the tags from webpage
    tag_names = names.split(",").collect {|str| str.strip.downcase}.uniq
    new_or_existing_tags = tag_names.collect {|tag_name| Tag.find_or_create_by(name: tag_name) }

    self.tags = new_or_existing_tags
  end

end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :for_lease, class_name: "Lease", foreign_key: "lease_id"
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify

  validates :name, presence: true
  validates_uniqueness_of :name
  
end

app/models/tag.rb
class Tag < ApplicationRecord
  extend FriendlyId
  friendly_id :name
  paginates_per 5

  has_many :taggings, dependent: :destroy
  has_many :properties, through: :taggings

  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :property
  belongs_to :tag
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :property

  validates :subject, presence: true, length: {minimum: 5}
  validates :ticket_type, presence: true
  validates :property_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  paginates_per 15
  after_create :assign_default_role

  extend FriendlyId
  friendly_id :username, use: :slugged

  has_many :managed_properties, class_name: "Property", dependent: :destroy, inverse_of: 'landlord' #Using :inverse_of option, we can explicitly declare bi-directional associations:
  has_many :comments
  has_many :tickets

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable, :timeoutable, :lockable
  rolify #for rolify gem

  validates :first_name, presence: true, length: {minimum: 3}
  validates :last_name, presence: true, length: {minimum: 3}
  validates :username, presence: true, length: {minimum: 5}
  validate :must_have_a_role, on: :update

  def to_s
    "#{username}"
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def assign_default_role
    self.add_role :applicant if self.roles.blank?
  end

  def must_have_a_role
    unless roles.any?
      errors.add(:roles, "must have at least one role.")
    end
  end

end

app/models/vehicle.rb
#renter's vehicles

app/views/apps/_form.html.erb
<!-- Nav tabs -->
<p>
<ul class="nav nav-tabs" id="listingTab" role="tablist">
  <li class="nav-item" role="presentation"><a class="nav-link active" id="home-tab" data-toggle="tab" href="#tabpane1">Personal Information</a></li>
  <li class="nav-item" role="presentation"><a class="nav-link" id="info-tab" data-toggle="tab" href="#tabpane2">Addresses</a></li>
  <li class="nav-item" role="presentation"><a class="nav-link" id="rooms-tab" data-toggle="tab" href="#tabpane3">Income & Employment</a></li>
  <li class="nav-item" role="presentation"><a class="nav-link" id="lease-tab" data-toggle="tab" href="#tabpane4">Certification</a></li>
  <li class="nav-item" role="presentation"><a class="nav-link" id="showing-tab" data-toggle="tab" href="#tabpane5">Attachments</a></li>
</ul>

<!-- Tab panes -->
<%= simple_form_for(app) do |f| %>

<div class="tab-content" id="listingTabContent">
  <div class="tab-pane fade show active" id="tabpane1" role="tabpanel">
    <%= render "tabpane1", f: f %>
  </div>
  <div class="tab-pane fade" id="tabpane2" role="tabpanel">
    <%= render "tabpane2", f: f %>
  </div>
  <div class="tab-pane fade" id="tabpane3" role="tabpanel">
    <%= render "tabpane3", f: f %>
  </div>
  <div class="tab-pane fade" id="tabpane4" role="tabpanel">
    <%= render "tabpane4", f: f %>
  </div>
  <div class="tab-pane fade" id="tabpane5" role="tabpanel">
    <%= render "tabpane5", f: f %>
  </div>
</div>

<%= f.button :submit, class: "btn btn-primary"%> <%= link_to "Cancel", listings_path, class: "btn btn-secondary" %>
<% end %>

app/views/apps/_tabpane1.html.erb
<%# Personal Information %>
<%= f.input :move_in_date %>
<%= f.input :lease_term_requested %>
<%= f.input :emergency_contact_name %>
<%= f.input :emergency_contact_phone %>
<%= f.input :emergency_contact_email %>
<%= f.input :emergency_contact_address1 %>
<%= f.input :emergency_contact_address2 %>
<%= f.input :emergency_contact_city %>
<%= f.input :emergency_contact_state %>
<%= f.input :emergency_contact_country %>

app/views/apps/_tabpane2.html.erb
<%# Prior Addresses %>
<h4>Please provide details of current and prior addresses.</h4>

app/views/apps/_tabpane3.html.erb
<%# Income and Employment %>
<h4>Please provide details of current and prior employment.</h4>

app/views/apps/_tabpane4.html.erb
<%# Certification %>
<%= f.input :water_bed_flag %>
<%= f.input :smoker_flag %>
<%= f.input :renters_insurance_flag %>
<%= f.input :military_flag %>
<%= f.input :one_year_military_stay_flag %>
<%= f.input :eviction_flag %>
<%= f.input :asked_to_move_out_flag %>
<%= f.input :ever_breached_lease_flag %>
<%= f.input :bankruptcy_flag %>
<%= f.input :foreclosure_flag %>
<%= f.input :credit_problem_flag %>
<%= f.input :crime_conviction_flag %>
<%= f.input :sex_offender_flag %>
<%= f.input :credit_check_authorization_flag %>
<%= f.input :additional_information %>

app/views/apps/_tabpane5.html.erb
<%# Attachments %>
<h4>Please submit copies of following documents</h4>
<ul>
<li>Social Security card</li>
<li>Driver's license</li>
<li>Paystubs for Last 2 months</li>
</ul>

app/views/apps/edit.html.erb
<% provide(:title, @apps.title) %>

<header>
  <h1>Edit Rental Application</h1>
</header>

<%= render "form", apps: @apps %>

app/views/apps/index.html.erb
<h1>Index page for Rental applications</h1>

app/views/apps/new.html.erb
<header>
  <h1 class="col-12">New Rental Application for @listing.title</h1>
</header>

<%= render "form", app: @app %>

app/views/apps/show.html.erb
<% provide(:title, @apps.title) %>

<header>
  <h1>Rental Application</h1>
  <ul>
    <%= link_to "Edit", edit_app_path(@app), class: "edit" if policy(@app).edit? %>
    <%= link_to "Delete", listing_path(@app), method: :delete, class: "delete", data: {confirm: "Are you sure?"} if policy(@app).destroy? %>
  </ul>
</header>

<div class="row">
  <h3>Show page for Rental application</h3>
</div>