config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  post '/webhook_events/:source', to: 'webhook_events#create'
  #source could be stripe or github or twilio or facebook etc.

  namespace :admin do
    root 'application#index'
    resources :users
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :expenses, only: [:index]
    resources :listings, only: [:index]
    resources :apps, only: [:index]
    resources :leases, only: [:index]
    resources :tickets, only: [:index]
  end

  resources :users, only: [:show]
  resources :categories, only: [:show]
  resources :tags, only: [:show]
  resources :expenses
  resources :tickets, only: [:index, :show, :new, :create]

  resources :properties do
    #resources :expenses, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :comments, only: [:create]
    resources :likes, only: [:create]
  end

  resources :listings do
  end

  resources :apps

  resources :leases do
    resources :payments
    resources :receipts, only: [:index, :show, :destroy]
  end

end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  paginates_per 3

  validates :name, presence: true, length: { minimum: 5 }
  validates_uniqueness_of :name

  has_many :properties
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.order(:name).page params[:page]
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:success] = "Category created successfully."
      redirect_to admin_categories_path
    else
      flash[:warning] = "Category not created."
      render "new"
    end
  end

  def edit

  end

  def update
    if @category.update(category_params)
      flash[:success] = "Category updated."
      redirect_to admin_categories_path
    else
      flash.now[:warning] = "Category not updated."
      render "edit"
    end
  end

  def destroy
    if @category.destroy
      flash[:danger] = "Category deleted."
      redirect_to admin_categories_path
    else
      flash.now[:warning] = "Category not deleted."
      redirect_to admin_categories_path
    end
  end

  private

    def set_category
      @category = Category.friendly.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        flash[:danger] = "The page you requested does not exist."
        redirect_to admin_categories_path
    end

    def category_params
      params.require(:category).permit(:name, :summary)
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]
  before_action :authenticate_user!, except: [:show]
  skip_after_action :verify_authorized

  def show
    @categories = Category.order(:name)
    @category_properties = @category.properties.order(created_at: :desc).page params[:page]
  end

  private
    def set_category
      @category = Category.friendly.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        flash[:danger] = "The category you requested does not exist."
        redirect_to(request.referrer || properties_url)
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/show.html.erb
<% provide(:title, @category.name ) %>

<header>
  <h1 class="col-12 text-uppercase"><%= @category.name %> <small>type properties</small></h1>

  <ul class="actions">
    <% admins_only do %>
      <li><%= link_to "Edit", edit_admin_category_path(@category), class: "edit" %></li>
      <li><%= link_to "Delete", admin_category_path(@category), method: :delete, data: {confirm: "Are you sure?"}, class: "delete" %></li>
    <% end %>
  </ul>
</header>

<div class="row">
  <div class="col-3 sidebar">
    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
      <h3 class="discover">Discover</h3>
      <ul class="nav nav-pills flex-column">
        <li class="nav-item <%= "active" if current_page?("/properties")%>">
          <%= link_to "ALL PROPERTIES", properties_path, class: "nav-link" %> <%= "active" if current_page?("/properties")%>
        </li>
      </ul>
      <ul class="nav flex-column nav-pills">
        <% @categories.each do |category| %>
          <li class="nav-item <%= "active" if current_page?("/categories/#{category.id}")%> text-uppercase">
            <%= link_to category.name, category_path(category), class: "nav-link #{ "active" if current_page?("/categories/#{category.slug}")}" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="col-9">
    <h4>Discover and apply to your favorite properties right here</h4>

    <% @category_properties.each do |property| %>
       <%= link_to property_path(property) do %>
        <div class="properties">
          <div class="row">
            <div class="col-sm-3">
              <% if property.image.attached? %>
                <%= image_tag property.image, style: "width: 200px; display: block" %>
              <% else %>
                <%= "Image missing" %>
              <% end %>
            </div>
            <div class="col-sm-9">
              <h3><%= property.title %></h3>
              <p><%= property.city %></p>
              <p><%= property.state %></p>
              <p><%= property.country %></p>
              <p><%= property_status(property) %></p>
              <p class="index-icons">
                <span><%= fa_icon "comments" %></span>
                <span><%= fa_icon "thumbs-o-up" %></span>
                <span><%= fa_icon "thumbs-o-down" %></span>
              </p>
            </div>
          </div>
        </div>
       <% end %>
    <% end %>
    <%= paginate @category_properties %>
  </div>
</div>